function [] = genSpatialFigExp(fignum,Pexp,eulexp,t)
figure(fignum);subplot(2,3,1);hold on;plot(t,Pexp(1,:),'LineWidth',2);title('X')
xlabel('Time (s)');ylabel('Position (m)')
subplot(2,3,2);hold on;plot(t,Pexp(2,:),'LineWidth',2);title('Y')
xlabel('Time (s)');ylabel('Position (m)')
subplot(2,3,3);hold on;plot(t,Pexp(3,:),'LineWidth',2);title('Z')
xlabel('Time (s)');ylabel('Position (m)')
subplot(2,3,4);hold on;plot(t,eulexp(3,:)*180/pi,'LineWidth',2);title('Roll')
xlabel('Time (s)');ylabel('Orientation (deg)')
subplot(2,3,5);hold on;plot(t,eulexp(2,:)*180/pi,'LineWidth',3);title('Pitch')
xlabel('Time (s)');ylabel('Orientation (deg)')
subplot(2,3,6);hold on;plot(t,eulexp(1,:)*180/pi,'LineWidth',2);title('Yaw')
xlabel('Time (s)');ylabel('Orientation (deg)')
end