function [] = genSpatialFigDes_Dual(fignum,Pdes,euldes,t)
figure(fignum);subplot(2,3,1);hold on;plot(t,Pdes(1,:),'k','LineWidth',2);title('X')
xlabel('Time (s)');ylabel('Position (m)')
subplot(2,3,2);hold on;plot(t,Pdes(2,:),'k','LineWidth',2);title('Y')
xlabel('Time (s)');ylabel('Position (m)')
subplot(2,3,3);hold on;plot(t,Pdes(3,:),'k','LineWidth',2);title('Z')
xlabel('Time (s)');ylabel('Position (m)')
subplot(2,3,4);hold on;plot(t,euldes(3,:)*180/pi,'k','LineWidth',2);title('Roll')
xlabel('Time (s)');ylabel('Orientation (deg)')
subplot(2,3,5);hold on;plot(t,euldes(2,:)*180/pi,'k','LineWidth',3);title('Pitch')
xlabel('Time (s)');ylabel('Orientation (deg)')
subplot(2,3,6);hold on;plot(t,euldes(1,:)*180/pi,'k','LineWidth',2);title('Yaw')
xlabel('Time (s)');ylabel('Orientation (deg)')
end